import sys
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

block_cipher = None

hidden_imports = [
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.lifespan.off",
    "aiosqlite",
    "sqlalchemy.dialects.sqlite",
    "sqlalchemy.ext.asyncio",
    "fastapi",
    "pydantic",
    "pydantic_settings",
    "openai",
    "httpx",
    "dotenv",
    "multipart",
    "chromadb",
    "pypdf",
    "docx",
    "bs4",
    "openpyxl",
    "reportlab",
    "chardet",
]

datas = [
    ("prompts", "prompts"),
]

excludes = [
    "pytest",
    "pytest_asyncio",
    "_pytest",
    "tkinter",
    "unittest",
    "test",
    "tests",
    "torch",
    "torchvision",
    "torchaudio",
    "tensorflow",
    "keras",
    "sklearn",
    "scipy",
    "matplotlib",
    "cv2",
    "numba",
    "llvmlite",
    "spacy",
    "thinc",
    "transformers",
    "datasets",
    "plotly",
    "skimage",
    "xarray",
    "h5py",
    "altair",
    "narwhals",
    "srsly",
    "bitsandbytes",
    "av",
    "emoji",
    "boto3",
    "botocore",
    "grpc",
    "google",
    "pdfminer",
    "pypdfium2",
    "win32com",
    "pythoncom",
    "pywintypes",
    "sentry_sdk",
    "pydub",
    "unstructured",
    "openxlab",
    "langchain",
    "langchain_core",
]

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="ai-exam-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
